name: Git Commit on Workflow
description: Commit when a file has changed during the Workflow
author: Matheus Albino
branding:
  icon: git-commit
  color: blue
inputs:
  github-token:
    description: Github Token
    required: true
  user-name:
    description: Git user.name
    required: false
    default: Github Actions - Git Commit
  user-email:
    description: Git user.email
    required: false
    default: github-actions-git-commit@users.noreply.github.com
  message:
    description: Git message
    required: false
    default: "Github Actions - Git Commit"
  tag:
    description: Git tag to place on commit
    required: false
    default: "no-build"
runs:
  using: node12
  main: lib/index.js
